language: java
sudo: required
dist: trusty
group: edge

addons:
  sonarcloud:
    organization: trellis-ldp

services:
  - mysql

before_script:
  - psql -c 'create database trellis;' -U postgres
  - mysql -e 'CREATE DATABASE trellis;'

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

matrix:
  fast_finish: true

  include:
    # JDK 8
    - jdk: oraclejdk8
      after_success: ./gradlew jacocoRootReport coveralls sonarqube

    # JDK 10
    - jdk: oraclejdk10

    # JDK 11
    - jdk: oraclejdk11

  allow_failures:
    - jdk: oraclejdk11

script: ./gradlew clean check install --info
